apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: lorem-ipsum-gateway
  namespace: istio-ingress
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      credentialName: istio-ca-secret
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: lorem-ipsum-dev-vs
  namespace: istio-ingress
spec:
  hosts:
  - "*"
  gateways:
  - lorem-ipsum-gateway
  http:
  - match:
      - uri:
          prefix: /books
    route:
    - destination:
        port:
          number: 8000
        host: lorem-ipsum.dev.svc.cluster.local