apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: lorem-ipsum-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingress # use Istio default gateway implementation
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    hosts:
    - "*"
    tls:
      mode: SIMPLE
      credentialName: lorem-ipsum-dev-ca-secret

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: lorem-ipsum-vs
  namespace: istio-system
spec:
  hosts:
  - "lorem.ipsum.dev"
  gateways:
  - lorem-ipsum-gateway
  http:
  - match:
    - uri:
        prefix: "/books"
    route:
    - destination:
        port:
          number: 80
        host: lorem-ipsum.dev.svc.cluster.local