kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-storage
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: vol0
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  local:
    path: /Users/adriandolha/data/vol0
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - docker-desktop
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: vol1
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  local:
    path: /Users/adriandolha/data/vol1
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - docker-desktop
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: vol1
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  local:
    path: /Users/adriandolha/data/vol1
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - docker-desktop
kind: PersistentVolume
apiVersion: v1
metadata:
  name: vol2
  labels:
    type: local
spec:
  capacity:
    storage: 5Gi
  local:
    path: /Users/adriandolha/data/vol2
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
              - docker-desktop
---