apiVersion: apps/v1
kind: Deployment
metadata:
  name: covid19
  namespace: demo
  labels:
    app: covid19
spec:
  replicas: 1
  selector:
    matchLabels:
      app: covid19
  template:
    metadata:
      labels:
        app: covid19
    spec:
      containers:
      - name: covid19
        image: 103050589342.dkr.ecr.eu-central-1.amazonaws.com/covid19:dev
        imagePullPolicy: "Always"
        env:
          - name: app_env
            value: "kube"
          - name: aurora_user
            value: "postgres"
          - name: aurora_host
            value: "existing-peahen-postgresql.default.svc.cluster.local"
          - name: aurora_port
            value: "5432"
          - name: aurora_password
            valueFrom:
              secretKeyRef:
                name: existing-peahen-postgresql
                key: postgresql-password
        livenessProbe:
          httpGet:
            path: /symptoms/health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 5
      - name: covid19-prometheus
        image: 103050589342.dkr.ecr.eu-central-1.amazonaws.com/covid19-prometheus:dev
        imagePullPolicy: "Always"
      - name: statsd-exporter
        image: prom/statsd-exporter:latest
