---
kind: Service
apiVersion: v1
metadata:
  name: covid19
  namespace: demo
spec:
  type: NodePort
  selector:
    app: covid19
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30500
---
kind: Service
apiVersion: v1
metadata:
  name: pandemic-support
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: covid19
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: covid19-prometheus-np
  namespace: demo
spec:
  type: NodePort
  selector:
    app: covid19
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
    nodePort: 30501
---
kind: Service
apiVersion: v1
metadata:
  name: covid19-prometheus-cip
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: covid19
  ports:
  - protocol: TCP
    port: 9090
    targetPort: 8081
---
kind: Service
apiVersion: v1
metadata:
  name: covid19-statsd-np
  namespace: demo
spec:
  type: NodePort
  selector:
    app: covid19
  ports:
  - protocol: TCP
    nodePort: 30502
    targetPort: 9102
    port: 9102
