kind: Service
apiVersion: v1
metadata:
  name: covid19
  namespace: demo
spec:
  type: NodePort
  selector:
    app: covid19
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
    nodePort: 30101