apiVersion: v1
kind: Service
metadata:
  name: postgres-nodeport
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 5432
    nodePort: 31452
    targetPort: 5432
  selector:
    app.kubernetes.io/instance: postgres
    app.kubernetes.io/name: postgresql