apiVersion: apps/v1
kind: Deployment
metadata:
  name: lorem-ipsum
  namespace: dev
  labels:
    app: lorem-ipsum
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lorem-ipsum
      version: v1
  template:
    metadata:
      labels:
        app: lorem-ipsum
        version: v1
    spec:
      containers:
        - name: lorem-ipsum
          image: lorem-ipsum:dev
          #          imagePullPolicy: "Always"
          env:
            - name: app_env
              value: "kube"
            - name: database_name
              valueFrom:
                secretKeyRef:
                  name: lorem-ipsum
                  key: aurora-database
            - name: aurora_user
              valueFrom:
                secretKeyRef:
                  name: lorem-ipsum
                  key: aurora-user
            - name: aurora_host
              valueFrom:
                secretKeyRef:
                  name: lorem-ipsum
                  key: aurora-host
            - name: aurora_port
              valueFrom:
                secretKeyRef:
                  name: lorem-ipsum
                  key: aurora-port
            - name: aurora_password
              valueFrom:
                secretKeyRef:
                  name: postgresql
                  key: postgresql-password
            - name: admin_user
              valueFrom:
                secretKeyRef:
                  name: lorem-ipsum
                  key: admin-user
            - name: admin_password
              valueFrom:
                secretKeyRef:
                  name: lorem-ipsum
                  key: admin-password
            - name: password_encryption_key
              valueFrom:
                secretKeyRef:
                  name: lorem-ipsum
                  key: password-encryption-key
            - name: pod_name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          livenessProbe:
            httpGet:
              path: /books/health
              port: 8000
            initialDelaySeconds: 3
            periodSeconds: 5
          volumeMounts:
            - mountPath: /jwk/certs
              name: jwk-certs
        - name: statsd-exporter
          image: prom/statsd-exporter:latest
      volumes:
        - name: jwk-certs
          secret:
            secretName: jwk-certs
            items:
              - key: public.key
                path: public.key
              - key: private.key
                path: private.key
---
kind: Service
apiVersion: v1
metadata:
  name: lorem-ipsum
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: lorem-ipsum
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: lorem-ipsum-prometheus
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: lorem-ipsum
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 8081
---
kind: Service
apiVersion: v1
metadata:
  name: lorem-ipsum-statsd
  namespace: dev
spec:
  type: ClusterIP
  selector:
    app: lorem-ipsum
  ports:
    - protocol: TCP
      targetPort: 9102
      port: 9102

