apiVersion: v1
kind: Service
metadata:
  labels:
    app: connector-lorem-ipsum-tasks-flower
  name: connector-lorem-ipsum-tasks-flower
  namespace: airflow
  annotations:
        service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  ports:
  - name: connector-lorem-ipsum-tasks-flower
    port: 5555
  selector:
    app: connector-lorem-ipsum-tasks-flower
