apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: connector-lorem-ipsum-tasks-flower
  namespace: airflow
spec:
  selector:
    matchLabels:
      app: connector-lorem-ipsum-tasks-flower
  template:
    metadata:
      labels:
        app: connector-lorem-ipsum-tasks-flower
    spec:
      containers:
      - image: 103050589342.dkr.ecr.eu-central-1.amazonaws.com/connector-lorem-ipsum-tasks-flower:1.6
        name: connector-lorem-ipsum-tasks-flower
        env:
          # Use secret in real usage
        - name: CELERY_BROKER_URL
          value: "redis://:airflow@airflow-redis-master:6379/0"