apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-registry
  namespace: demo
  labels:
    app: docker-registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: docker-registry
  template:
    metadata:
      labels:
        app: docker-registry
    spec:
      containers:
        - name: docker-registry
          image: registry:2.6.2
#          imagePullPolicy: "Always"
          env:
            - name: REGISTRY_HTTP_TLS_CERTIFICATE
              value: "/certs/tls.crt"
            - name: HTTP_PROXY
              value: "http://0.0.0.0:5000"
            - name: REGISTRY_HTTP_PROXY
              value: "http://0.0.0.0:5000"
            - name: REGISTRY_HTTP_TLS_KEY
              value: "/certs/tls.key"
            - name: REGISTRY_VALIDATION_DISABLED
              value: "true"
            - name: REGISTRY_LOG_LEVEL
              value: "debug"
          volumeMounts:
            - mountPath: /certs
              name: certs
      volumes:
        - name: certs
          secret:
            secretName: tls-cert
            items:
              - key: tls.crt
                path: tls.crt
              - key: tls.key
                path: tls.key
---
kind: Service
apiVersion: v1
metadata:
  name: docker-registry
  namespace: demo
spec:
  type: ClusterIP
  selector:
    app: docker-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000

#kubectl get secret tls-cert --namespace=default -o yaml  \
#| sed s/"namespace: default"/"namespace: demo"/\
#| kubectl apply -n demo -f -