kind: Service
apiVersion: v1
metadata:
  name: docker-registry-np
  namespace: default
spec:
  type: NodePort
  selector:
    app: docker-registry
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31111
