apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lorem-ipsum-source-ws
  namespace: tekton-pipelines
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lorem-ipsum-argocd-ws
  namespace: tekton-pipelines
spec:
  resources:
    requests:
      storage: 500Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: lorem-ipsum-pipeline
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: source
    - name: argocd
  params:
    - name: image-url
      type: string
      description: Docker registry image url.
    - name: repo-url
      type: string
      description: The git repository URL to clone from.
    - name: branch-name
      type: string
      description: The git depth to clone.
    - name: argocd-repo-url
      type: string
      description: The git repository URL to clone from.
    - name: argocd-branch-name
      type: string
      description: The git depth to clone.
    - name: depth
      type: string
      description: The clone depth.
      default: "0"
  tasks:
    - name: clean
      taskRef:
        name: clean
      workspaces:
        - name: source
          workspace: source
    - name: fetch-source-repo
      taskRef:
        name: git-clone
      runAfter:
        - clean
      workspaces:
        - name: output
          workspace: source
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch-name)
        - name: depth
          value: $(params.depth)
    - name: fetch-argocd-repo
      taskRef:
        name: git-clone
      runAfter:
        - fetch-source-repo
      workspaces:
        - name: output
          workspace: argocd
      params:
        - name: url
          value: $(params.argocd-repo-url)
        - name: revision
          value: $(params.argocd-branch-name)
        - name: depth
          value: $(params.depth)
    - name: prepare
      taskRef:
        name: prepare
      runAfter:
        - fetch-argocd-repo
      params:
        - name: url
          value: $(params.repo-url)
        - name: imageUrl
          value: $(params.image-url)
      workspaces:
        - name: source
          workspace: source
    - name: unit-test
      taskRef:
        name: pytest
      runAfter:
        - prepare
      workspaces:
        - name: source
          workspace: source
      params:
        - name: ARGS
          value: tests
        - name: version
          value: "$(tasks.prepare.results.version)"
        - name: WORKING_DIR
          value: "$(workspaces.source.path)/lorem-ipsum-eks/lorem-ipsum"
    - name: build-docker-image
      taskRef:
        name: build-docker-image-from-git-source
      runAfter:
        - unit-test
      workspaces:
        - name: source
          workspace: source
      params:
        - name: pathToDockerFile
          value: Dockerfile
        - name: pathToContext
          value: /workspace/source/lorem-ipsum-eks/lorem-ipsum #configure: may change according to your source
        - name: imageTag
          value: "$(tasks.prepare.results.imageTag)"
        - name: imageUrl
          value: "$(tasks.prepare.results.imageUrl)"
    - name: argocd
      taskRef:
        name: argocd-push
      runAfter:
        - build-docker-image
      workspaces:
        - name: source
          workspace: argocd
      params:
        - name: path
          value: /workspace/source/lorem-ipsum/values.yaml
        - name: imageTag
          value: "$(tasks.prepare.results.imageTag)"
---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: lorem-ipsum-pipeline-run
  namespace: tekton-pipelines
spec:
  serviceAccountName: git-push-service-account
  pipelineRef:
    name: lorem-ipsum-pipeline
  params:
    - name: repo-url
      value: git@github.com:adriandolha/cloud-demo.git
    - name: branch-name
      value: master
    - name: argocd-repo-url
      value: git@github.com:adriandolha/lorem-ipsum-argocd.git
    - name: argocd-branch-name
      value: main
    - name: image-url
      value: "docker-registry.internal:31111/lorem-ipsum"
  workspaces:
    - name: source
      persistentVolumeClaim:
        claimName: lorem-ipsum-source-ws
    - name: argocd
      persistentVolumeClaim:
        claimName: lorem-ipsum-argocd-ws
