nodeExporter:
  hostRootfs: false
resources:
  limits:
    cpu: 200m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 30Mi
podSecurityPolicy:
  enabled: false
server:
  persistentVolume:
    enabled: false
extraScrapeConfigs: |
  - job_name: 'envoy-stats'
    metrics_path: /stats/prometheus
    kubernetes_sd_configs:
    - role: pod

    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_container_port_name]
      action: keep
      regex: '.*-envoy-prom'
  - job_name: 'istiod'
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - istio-system
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: istiod;http-monitoring
  - job_name: loremipsum
    static_configs:
      - targets: ['lorem-ipsum.dev.svc.cluster.local', 'lorem-ipsum.test.svc.cluster.local']
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: loremipsumgu
    static_configs:
      - targets: ['lorem-ipsum-statsd.dev.svc.cluster.local:9102', 'lorem-ipsum-statsd.test.svc.cluster.local:9102']
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - http://prometheus.${namespace}.svc.cluster.local:9090/-/healthy
        - http://grafana.${namespace}.svc.cluster.local/api/health
        - http://lorem-ipsum.dev.svc.cluster.local/books/health
        - http://lorem-ipsum.test.svc.cluster.local/books/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus-blackbox-exporter.${namespace}:9115  # The blackbox exporter's real host:port.