nodeExporter:
  hostRootfs: false
resources:
  limits:
    cpu: 200m
    memory: 50Mi
  requests:
    cpu: 100m
    memory: 30Mi
podSecurityPolicy:
  enabled: false
server:
  persistentVolume:
    enabled: false
extraScrapeConfigs: |
  - job_name: loremipsum
    static_configs:
      - targets: ['lorem-ipsum.${namespace}.svc.cluster.local']
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: loremipsumgu
    static_configs:
      - targets: ['lorem-ipsum-statsd.${namespace}.svc.cluster.local:9102']
    scrape_interval: 5s
    scrape_timeout: 4s

  - job_name: 'blackbox'
    metrics_path: /probe
    params:
      module: [http_2xx]  # Look for a HTTP 200 response.
    static_configs:
      - targets:
        - https://localhost:31862/ambassador/v0/check_ready
        - http://prometheus.${namespace}:9090/-/healthy
        - http://grafana.${namespace}/api/health
        - http://lorem-ipsum.${namespace}/books/health
        - http://lorem-ipsum-auth.${namespace}/auth/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: prometheus-blackbox-exporter.${namespace}:9115  # The blackbox exporter's real host:port.